# Generated by Django 5.2.17 on 2026-08-18 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Solution', max_length=255)),
                ('content', models.TextField()),
                ('github_repo_url', models.URLField(blank=True, default='', max_length=500)),
                ('live_demo_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted'), ('FINALIST', 'Finalist'), ('WINNER', 'Winner'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=20)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('challenge', 'solver')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=150)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission')),
            ],
            options={
                'db_table': 'submission_files',
            },
        ),
    ]
