# Generated by Django 5.2.17 on 2026-08-18 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(default='General', max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('FUNDED', 'Funded'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('JUDGING', 'Judging'), ('WINNER_SELECTED', 'Winner Selected'), ('DISPUTED', 'Disputed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('visibility', models.CharField(default='PUBLIC', max_length=20)),
                ('ip_terms', models.TextField(blank=True, default='')),
                ('rules', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
                ('selected_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('priority', models.SmallIntegerField(default=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='challenges.challenge')),
            ],
            options={
                'db_table': 'challenge_requirements',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'challenge_skills',
                'unique_together': {('challenge', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='challenges', through='challenges.ChallengeSkill', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='PrizeAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_allocations', to='challenges.challenge')),
            ],
            options={
                'db_table': 'prize_allocations',
                'ordering': ['rank'],
                'unique_together': {('challenge', 'rank')},
            },
        ),
    ]
