# Generated by Django 5.2.17 on 2026-08-18 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('CHALLENGE_CREATED', 'Challenge Created'), ('CHALLENGE_PUBLISHED', 'Challenge Published'), ('CHALLENGE_FUNDED', 'Challenge Funded'), ('PAYMENT_SUCCESS', 'Payment Success'), ('SUBMISSION_CREATED', 'Submission Created'), ('SUBMISSION_SHORTLISTED', 'Submission Shortlisted'), ('WINNER_SELECTED', 'Winner Selected'), ('PAYOUT_CREATED', 'Payout Created'), ('PAYOUT_SUCCESS', 'Payout Success'), ('DISPUTE_OPENED', 'Dispute Opened'), ('DISPUTE_RESOLVED', 'Dispute Resolved')], db_index=True, max_length=50)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
