# Generated by Django 5.2.17 on 2026-08-18 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.UUIDField(db_index=True)),
                ('entry_type', models.CharField(choices=[('CHALLENGE_FUNDING', 'Challenge Funding'), ('WINNER_PAYOUT', 'Winner Payout'), ('PLATFORM_FEE', 'Platform Fee'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit (Inflow to Platform Escrow)'), ('DEBIT', 'Debit (Outflow to Recipient / Gateway)')], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
